spring:
  application:
    name: client-demo
#  redis:
#    database: 2
#    host: localhost
#    port: 32768
#    password: 1qaz@WSX
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    timeout: 100ms
server:
  port: 6100
#  servlet:
#    context-path: /client-demo

security:
  oauth2:
    client:
      client-id: client-demo
      client-secret: client-demo-secret-8888
      user-authorization-uri: http://localhost:6001/oauth/authorize
      access-token-uri: http://localhost:6001/oauth/token
#    resource:
#      id: user-client
#      user-info-uri: user-info
#    authorization:
#      check-token-access: http://localhost:6001/oauth/check_token
    resource:
      jwt:
        key-uri: http://localhost:6001/oauth/token_key
        key-value: dev
